package com.kinl.tmall.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.orderCode
     *
     * @mbggenerated
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.receiver
     *
     * @mbggenerated
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.userMessage
     *
     * @mbggenerated
     */
    private String usermessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.createDate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.payDate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.deliveryDate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date deliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.confirmDate
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date confirmdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.id
     *
     * @return the value of order_.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.id
     *
     * @param id the value for order_.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.orderCode
     *
     * @return the value of order_.orderCode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.orderCode
     *
     * @param ordercode the value for order_.orderCode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.address
     *
     * @return the value of order_.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.address
     *
     * @param address the value for order_.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.post
     *
     * @return the value of order_.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.post
     *
     * @param post the value for order_.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.receiver
     *
     * @return the value of order_.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.receiver
     *
     * @param receiver the value for order_.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.mobile
     *
     * @return the value of order_.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.mobile
     *
     * @param mobile the value for order_.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.userMessage
     *
     * @return the value of order_.userMessage
     *
     * @mbggenerated
     */
    public String getUsermessage() {
        return usermessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.userMessage
     *
     * @param usermessage the value for order_.userMessage
     *
     * @mbggenerated
     */
    public void setUsermessage(String usermessage) {
        this.usermessage = usermessage == null ? null : usermessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.createDate
     *
     * @return the value of order_.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.createDate
     *
     * @param createdate the value for order_.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.payDate
     *
     * @return the value of order_.payDate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.payDate
     *
     * @param paydate the value for order_.payDate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.deliveryDate
     *
     * @return the value of order_.deliveryDate
     *
     * @mbggenerated
     */
    public Date getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.deliveryDate
     *
     * @param deliverydate the value for order_.deliveryDate
     *
     * @mbggenerated
     */
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.confirmDate
     *
     * @return the value of order_.confirmDate
     *
     * @mbggenerated
     */
    public Date getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.confirmDate
     *
     * @param confirmdate the value for order_.confirmDate
     *
     * @mbggenerated
     */
    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.uid
     *
     * @return the value of order_.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.uid
     *
     * @param uid the value for order_.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.status
     *
     * @return the value of order_.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.status
     *
     * @param status the value for order_.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ordercode=").append(ordercode);
        sb.append(", address=").append(address);
        sb.append(", post=").append(post);
        sb.append(", receiver=").append(receiver);
        sb.append(", mobile=").append(mobile);
        sb.append(", usermessage=").append(usermessage);
        sb.append(", createdate=").append(createdate);
        sb.append(", paydate=").append(paydate);
        sb.append(", deliverydate=").append(deliverydate);
        sb.append(", confirmdate=").append(confirmdate);
        sb.append(", uid=").append(uid);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}