## 端口配置
server:
  port: 8080

## log配置
logging:
  level:
    root: info
    com.kinl.tmall: debug
  file:
    path: log/t-mall.log


spring:
  ## mysql配置
  datasource:
    url: jdbc:mysql://47.105.164.91:3306/tmall?serverTimezone=UTC&characterEncoding=utf-8&userSSL=false&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html;charset=utf-8
    cache: false
  #热部署
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**,webapp/**
  #redis
  redis:
    host: 47.105.164.91
    port: 6379
    ## Redis服务器连接密码（默认为空）
    #password: root
    ##超时连接时间(毫秒)
    timeout: 5000
    lettuce:
      pool:
        ##连接池中最大连接数
        max-active: 10
        ##连接池中最大空闲连接
        max-idle: 10
        ##连接池中最小空闲连接
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        min-idle: 0
#    jedis:
#      pool:
#        ##连接池中最大连接数
#        max-active: 10
#        ##连接池中最大空闲连接
#        max-idle: 10
#        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1


mybatis:
  type-aliases-package: com.kinl.tmall.pojo
  mapper-locations: classpath:mapper/*.xml

