## 端口配置
server:
  port: 8080

## log配置
logging:
  level:
    root: info
    com.kinl.tmall: debug
  file:
    path: log/t-mall.log


spring:
  ## mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/tmall?serverTimezone=UTC&characterEncoding=utf-8&userSSL=false&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html;charset=utf-8
    cache: false
  #热部署
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**,webapp/**

mybatis:
  type-aliases-package: com.kinl.tmall.pojo
  mapper-locations: classpath:mapper/*.xml

