package com.kinl.tmall.dao;

import com.kinl.tmall.pojo.Productimage;
import com.kinl.tmall.pojo.ProductimageExample;

import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductimageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int countByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int deleteByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int insert(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int insertSelective(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    List<Productimage> selectByExample(ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    Productimage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Productimage record, @Param("example") ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Productimage record, @Param("example") ProductimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Productimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Productimage record);

    ArrayList<Integer> findByIdAndSimple(Integer productId);

    ArrayList<Integer> findByIdAndDetails(Integer productId);

    Integer findFirstImage(Integer pid);

    Productimage findFirstImageByPid(Integer pid);

    List<Productimage> findAllSimpleByPid(Integer pid);

    List<Productimage> findAllDetailsByPid(Integer pid);
}