package com.kinl.tmall.dao;

import com.kinl.tmall.VO.PropertyValueVO;
import com.kinl.tmall.pojo.Propertyvalue;
import com.kinl.tmall.pojo.PropertyvalueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertyvalueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int countByExample(PropertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int deleteByExample(PropertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insert(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int insertSelective(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    List<Propertyvalue> selectByExample(PropertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    Propertyvalue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Propertyvalue record, @Param("example") PropertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Propertyvalue record, @Param("example") PropertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Propertyvalue record);

    Propertyvalue findByPtid(Integer ptid);

    Integer updateByPtid(Propertyvalue propertyvalue);

    List<Propertyvalue> findbyPid(Integer pid);

    Propertyvalue findByPidAndPtid(@Param("pid") Integer pid, @Param("ptid") Integer ptid);

    Integer insertVO(@Param("propertyValueVO") PropertyValueVO propertyValueVO);

    Integer updateVO(@Param("propertyValueVO") PropertyValueVO propertyValueVO);
}